### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by samueljohn** [ipython-contrib/IPython-extensions#11]
What am I doing wrong? Is it a temporary issue?

```
pip install ipyext
Collecting ipyext
  Could not find a version that satisfies the requirement ipyext (from versions: )
No matching distribution found for ipyext


pip --version
pip 7.1.2 from /Users/sam/anaconda/lib/python3.4/site-packages (python 3.4)
```

**Comment by jankatins** [comment]
Oups, we haven't yet uploaded a version to PyPI, so you have to install from source...

**Comment by jankatins** [comment]
@juhasch @Carreau Who is "allowed" to do a release here? Should I just make the push to PyPI?

**Comment by juhasch** [comment]
As you are the most active person here, I would say make the release.

**Comment by damianavila** [comment]
> As you are the most active person here, I would say make the release.

:+1:

**Comment by Carreau** [comment]
btw, should we consider [flit](http://flit.readthedocs.org/en/latest/) for packaging ?

**Comment by jankatins** [comment]
Re flit: I want to build conda packages and wheels via https://github.com/JanSchulz/package-builder and I think I need a setup.py for that.

**Comment by Carreau** [comment]
We can also try to figure out how to do that with flit at some point later then.

**Comment by jankatins** [comment]
Ok, uploaded a release to PyPi and conda (https://anaconda.org/janschulz/ipyext). conda release is done via https://github.com/JanSchulz/package-builder and currently uploading (win is slow...). I probably could also do the pypi release via the package builder, but was easier to upload the two versions by hand than figuring out how to only use one version (win vs mac vs linux) to upload them...

@samueljohn could you do a install and reopen if something is not working for you...

**Comment by samueljohn** [comment]
Thanks a lot. I can confirm it install fine and I can load it into IPython (tested with `%load_ext ipyext.writeandexecute` and `%load_ext ipyext.inactive`).

```
$ pip install --no-cache-dir ipyext
Collecting ipyext
  Downloading ipyext-0.1.0-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): ipython in /Users/sam/anaconda/lib/python3.4/site-packages (from ipyext)
Installing collected packages: ipyext
Successfully installed ipyext-0.1.0
```

On OS X 10.11.1, with `pip 7.1.2 from /Users/sam/anaconda/lib/python3.4/site-packages (python 3.4)`.
